#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'CV & Resume', url: 'pages/cvres.html'}
- {name: 'About', url: 'pages/about.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # About

   # Hi there! My name is Remy Stewart, and I’m currently a second-year PhD student at Cornell University. My program is housed in Sociology, but I’m lucky to be pursuing interdisciplinary training with Cornell’s Policy Analysis and Management and Information Science departments as well. My research stands at the intersection between social stratification scholarship, public policy, urban studies, and computational social science. 

   # Subject wise, I am interested in understanding how modern technological advances are reshaping longstanding American social structures and may be exasperating preexisting inequalities. My primary research project (and likely dissertation topic) is investigating Airbnb’s impact on affordable housing and gentrification within major metropolitan regions such as San Francisco and NYC. I’m also involved in a multitude of additional projects investigating contemporary changes in social policies such as food stamps, placed-based federal funding initiatives, and restorative justice programs in public schools. 

   # Methodologically, I am passionate about integrating traditional sociological qualitative methods with innovative techniques from machine learning and predictive modeling. I combine the latest within automatic topic modeling, NLP, and CNNs with cultural analytics to connect Big Data to subjective meaning-making and understanding human behavior. I’m also deeply invested in ethics, mitigating bias, and establishing best practices within computational social sciences and ML. I have written on research ethics related to consumer-based commercial datasets with a working paper currently under review. 

   # I was born and raised in the San Francisco Bay Area and obtained my bachelor’s at the University of California, Santa Cruz (go Banana Slugs!). I have a professional background in social services where I have previously managed a food pantry, facilitated food stamp applications, and interned for an emergency housing nonprofit. When I’m not either researching or coding I love to travel to cities, curate Spotify playlists, skateboard, and test out new vegetarian recipes. 

   # I’d love to get in touch, and you can reach me through my email at [rps256@cornell.edu] (mailto:rps256@cornell.edu).

#-------------------------------
# CV & Resume Section

CV & Resume: >

Here's my [academic CV] (link:#).
And here's my [industry resume] (link:#). 

#-------------------------------
# Work Section

projects:
- {name: 'Airbnb & Automatic Topic Modeling', folder: 'proj-1', file: 'projects/proj-1.html', image="projects/proj-1/thumb.jpg"}
- {name: 'TBA', folder: 'proj-2', file: 'projects/proj-2.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'envelope', link: 'mailto:rps256@cornell.edu'}
- {icon: 'github', link: 'https://github.com/remypstewart'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/remystewart-607/'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
